"use client";

/*
 * shadcn Sheet (radix Dialog), rebuilt on this project's tokens.
 *
 * As generated by the CLI this referenced shadcn defaults — `bg-background`,
 * `border`, `text-muted-foreground`, lucide's XIcon — none of which exist here
 * (shadcn's init never ran; see button.tsx for the same rebuild). So it is
 * retoken­ised onto `bg-white` / `text-ink` and the project's Phosphor icon.
 *
 * Enter/exit motion is CSS `@keyframes` in globals.css, not a transition:
 * radix drives the exit off `animationend`, so a plain transition would let the
 * panel unmount before it could animate out. The curve is the page's one
 * decelerate ease, so the drawer settles like every other surface.
 */

import * as React from "react";
import { Dialog as SheetPrimitive } from "radix-ui";
import { XIcon } from "@phosphor-icons/react/ssr";

import { cn } from "@/lib/utils";

function Sheet(props: React.ComponentProps<typeof SheetPrimitive.Root>) {
  return <SheetPrimitive.Root data-slot="sheet" {...props} />;
}

function SheetTrigger(
  props: React.ComponentProps<typeof SheetPrimitive.Trigger>,
) {
  return <SheetPrimitive.Trigger data-slot="sheet-trigger" {...props} />;
}

function SheetClose(props: React.ComponentProps<typeof SheetPrimitive.Close>) {
  return <SheetPrimitive.Close data-slot="sheet-close" {...props} />;
}

function SheetPortal(props: React.ComponentProps<typeof SheetPrimitive.Portal>) {
  return <SheetPrimitive.Portal data-slot="sheet-portal" {...props} />;
}

function SheetOverlay({
  className,
  ...props
}: React.ComponentProps<typeof SheetPrimitive.Overlay>) {
  return (
    <SheetPrimitive.Overlay
      data-slot="sheet-overlay"
      className={cn(
        "fixed inset-0 z-50 bg-ink/40 backdrop-blur-[2px]",
        "data-[state=open]:animate-[sheet-fade-in_0.4s_cubic-bezier(0.16,1,0.3,1)]",
        "data-[state=closed]:animate-[sheet-fade-out_0.3s_cubic-bezier(0.16,1,0.3,1)]",
        className,
      )}
      {...props}
    />
  );
}

const SIDE = {
  right:
    "inset-y-0 right-0 h-full w-4/5 max-w-sm data-[state=open]:animate-[sheet-in-right_0.5s_cubic-bezier(0.16,1,0.3,1)] data-[state=closed]:animate-[sheet-out-right_0.35s_cubic-bezier(0.16,1,0.3,1)]",
  left: "inset-y-0 left-0 h-full w-4/5 max-w-sm data-[state=open]:animate-[sheet-in-left_0.5s_cubic-bezier(0.16,1,0.3,1)] data-[state=closed]:animate-[sheet-out-left_0.35s_cubic-bezier(0.16,1,0.3,1)]",
  top: "inset-x-0 top-0 h-auto data-[state=open]:animate-[sheet-in-top_0.5s_cubic-bezier(0.16,1,0.3,1)] data-[state=closed]:animate-[sheet-out-top_0.35s_cubic-bezier(0.16,1,0.3,1)]",
  bottom:
    "inset-x-0 bottom-0 h-auto data-[state=open]:animate-[sheet-in-bottom_0.5s_cubic-bezier(0.16,1,0.3,1)] data-[state=closed]:animate-[sheet-out-bottom_0.35s_cubic-bezier(0.16,1,0.3,1)]",
} as const;

function SheetContent({
  className,
  children,
  side = "right",
  ...props
}: React.ComponentProps<typeof SheetPrimitive.Content> & {
  side?: keyof typeof SIDE;
}) {
  return (
    <SheetPortal>
      <SheetOverlay />
      <SheetPrimitive.Content
        data-slot="sheet-content"
        className={cn(
          "fixed z-50 flex flex-col gap-4 bg-white p-6 shadow-[0_1px_2px_rgb(0_0_0/0.04),0_24px_50px_-24px_rgb(0_0_0/0.4)] focus:outline-none",
          SIDE[side],
          className,
        )}
        {...props}
      >
        {children}
        <SheetPrimitive.Close
          className="absolute right-5 top-5 grid size-9 cursor-pointer place-items-center rounded-pill text-ink/70 transition-colors duration-200 hover:bg-ink/5 hover:text-ink focus:outline-none"
          aria-label="Close menu"
        >
          <XIcon size={22} aria-hidden />
        </SheetPrimitive.Close>
      </SheetPrimitive.Content>
    </SheetPortal>
  );
}

function SheetHeader({ className, ...props }: React.ComponentProps<"div">) {
  return (
    <div
      data-slot="sheet-header"
      className={cn("flex flex-col gap-1.5", className)}
      {...props}
    />
  );
}

function SheetFooter({ className, ...props }: React.ComponentProps<"div">) {
  return (
    <div
      data-slot="sheet-footer"
      className={cn("mt-auto flex flex-col gap-2", className)}
      {...props}
    />
  );
}

function SheetTitle({
  className,
  ...props
}: React.ComponentProps<typeof SheetPrimitive.Title>) {
  return (
    <SheetPrimitive.Title
      data-slot="sheet-title"
      className={cn("text-lg font-semibold text-ink", className)}
      {...props}
    />
  );
}

function SheetDescription({
  className,
  ...props
}: React.ComponentProps<typeof SheetPrimitive.Description>) {
  return (
    <SheetPrimitive.Description
      data-slot="sheet-description"
      className={cn("text-sm text-ink-muted", className)}
      {...props}
    />
  );
}

export {
  Sheet,
  SheetTrigger,
  SheetClose,
  SheetContent,
  SheetHeader,
  SheetFooter,
  SheetTitle,
  SheetDescription,
};
